# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

ADMIN = 'ADMIN'
CATEQUISTA = 'CATEQUISTA'
COORDENADOR = 'COORDENADOR'
CATEQUIZANDO = 'CATEQUIZANDO'

ALL_PERMISSIONS_LIST = [ADMIN, CATEQUISTA, COORDENADOR, CATEQUIZANDO]
